spring.application.name=notification-service



#----------------kafka config---------------#



server.port=8081

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.consumer.group-id=notification-service-group-2

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#spring.kafka.consumer.properties.spring.json.trusted.packages=com.notificationservice.kafka.event

#spring.kafka.consumer.properties.spring.json.value.default.type=com.notificationservice.kafka.event.UserRegisteredEvent


#==========actuator prop============
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.metrics.tags.application=${spring.application.name}
management.health.mail.enabled=false

#=================email config======================#
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#============jwt==============

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
